export function tracePayload() {
  return {
    run_id: "run_frontend_agent",
    lookup_snapshot_id: "lookup_frontend",
    workspace_id: "frontend_workspace",
    project_id: "frontend_project",
    site_id: null,
    objective: "Evaluate this lookup snapshot for agentic developer-value discovery.",
    status: "requires_review",
    ready_for_synthesis: false,
    evidence_ids: ["evidence-parcel", "evidence-zoning"],
    evidence_packets: [
      {
        evidence_id: "evidence-parcel",
        source_type: "parcel_appraiser",
        source_authority: "authoritative_public_record",
        source_title: "Recorded parcel appraiser packet",
        source_url: "https://bcpa.net/parcel/504210230010",
        retrieved_at: "2026-06-22T00:00:00Z",
        effective_date: "2026-01-01",
        parser_version: "parcel-parser@1",
        schema_version: "parcel-v1",
        raw_artifact_ref: "raw://parcel/evidence-parcel",
        referenced_field_keys: ["parcel.apn"],
        calculation_outputs: [],
        lineage: ["source", "raw_artifact", "normalized_evidence", "displayed_field"],
        confidence: 1,
        quality_score: 0.98,
        quality_flags: [],
        warnings: [],
      },
      {
        evidence_id: "evidence-zoning",
        source_type: "official_zoning_map",
        source_authority: "authoritative_public_record",
        source_title: "Recorded zoning map packet",
        source_url: "https://miramarfl.gov/zoning-map",
        retrieved_at: "2026-06-22T00:00:00Z",
        effective_date: "2026-01-15",
        parser_version: "zoning-map-parser@2",
        schema_version: "zoning-map-v2",
        raw_artifact_ref: "raw://zoning/evidence-zoning",
        referenced_field_keys: ["zoning.district"],
        calculation_outputs: ["max_units=2"],
        lineage: ["source", "raw_artifact", "normalized_evidence", "calculation_output"],
        confidence: 0.94,
        quality_score: 0.91,
        quality_flags: ["schema_stable"],
        warnings: [],
      },
    ],
    source_retrievals: [
      {
        evidence_id: "evidence-parcel",
        source_type: "parcel_appraiser",
        source_authority: "authoritative_public_record",
        publisher: "Broward County Property Appraiser",
        source_title: "Recorded parcel appraiser packet",
        source_url: "https://bcpa.net/parcel/504210230010",
        retrieved_at: "2026-06-22T00:00:00Z",
        effective_date: "2026-01-01",
        parser_version: "parcel-parser@1",
        schema_version: "parcel-v1",
        raw_artifact_ref: "raw://parcel/evidence-parcel",
        query_parameters: ["folio=504210230010"],
        referenced_field_keys: ["parcel.apn"],
        calculation_outputs: [],
        lineage: ["source", "raw_artifact", "normalized_evidence", "displayed_field"],
        quality_score: 0.98,
        quality_flags: [],
        warnings: [],
      },
      {
        evidence_id: "evidence-zoning",
        source_type: "official_zoning_map",
        source_authority: "authoritative_public_record",
        publisher: "City of Miramar",
        source_title: "Recorded zoning map packet",
        source_url: "https://miramarfl.gov/zoning-map",
        retrieved_at: "2026-06-22T00:00:00Z",
        effective_date: "2026-01-15",
        parser_version: "zoning-map-parser@2",
        schema_version: "zoning-map-v2",
        raw_artifact_ref: "raw://zoning/evidence-zoning",
        query_parameters: ["address=frontage"],
        referenced_field_keys: ["zoning.district"],
        calculation_outputs: ["max_units=2"],
        lineage: ["source", "raw_artifact", "normalized_evidence", "calculation_output"],
        quality_score: 0.91,
        quality_flags: ["schema_stable"],
        warnings: [],
      },
    ],
    warnings: [],
    open_questions: [],
    assignments: [
      {
        lane: "underwriting_analyst",
        objective: "Run deterministic development capacity checks.",
        field_keys: ["zoning.district"],
        evidence_ids: ["evidence-zoning"],
        calculation_outputs: ["max_units=2"],
        warnings: [],
        escalation_required: false,
      },
    ],
    escalations: [],
    trace_steps: [
      {
        sequence: 1,
        kind: "run_started",
        summary: "Run started from recorded lookup snapshot.",
        lane: null,
        field_keys: [],
        evidence_ids: [],
        calculation_outputs: [],
        warnings: [],
        escalation_required: false,
      },
    ],
    artifact: {
      status: "draft",
      report_id: "report_frontend_agent",
      document_id: "document_frontend_agent",
      evidence_ids: ["evidence-parcel", "evidence-zoning"],
      sections: [
        {
          id: "evidence_scope",
          title: "Evidence Scope",
          evidence_ids: ["evidence-parcel", "evidence-zoning"],
          claims: [
            {
              key: "evidence.scope",
              text: "The run summary is limited to recorded lookup evidence.",
              material: true,
              evidence_ids: ["evidence-parcel", "evidence-zoning"],
            },
          ],
        },
        {
          id: "deterministic_calculations",
          title: "Deterministic Calculations",
          evidence_ids: ["evidence-zoning"],
          claims: [
            {
              key: "calculation.underwriting_analyst.1",
              text: "Deterministic calculation output from underwriting_analyst: max_units=2.",
              material: true,
              evidence_ids: ["evidence-zoning"],
            },
          ],
        },
      ],
      opportunities: [
        {
          key: "opportunity.by_right_capacity",
          status: "hypothesis",
          current_verified_condition: "Recorded lookup evidence supports max_units=2.",
          proposed_scenario: "Test by-right development capacity using recorded zoning evidence.",
          required_zoning_entitlement_path:
            "By-right scenario only; entitlement upside remains unverified until official local evidence is retrieved.",
          calculation_outputs: ["max_units=2"],
          upside_mechanism:
            "Developer value may exist if the by-right unit yield exceeds the current use.",
          blocking_constraints: [
            "Market rents, costs, financing terms, and entitlement outcomes are not verified by the lookup snapshot.",
          ],
          evidence_ids: ["evidence-zoning"],
          assumptions: [
            "Market rents, costs, financing terms, exit values, and lender terms remain underwriting assumptions until sourced.",
          ],
          confidence: 0.6,
          next_verification_step:
            "Confirm market rents, costs, financing terms, and any missing dimensional standards before underwriting value.",
        },
      ],
      assumptions: [
        {
          key: "open_question.1",
          text: "standards.setbacks.front is unknown; retrieve authoritative evidence before use.",
          status: "requires_human_review",
          source: "agent_run.open_question",
          field_key: null,
        },
      ],
      message: null,
    },
    latest_eval: {
      eval_run_id: "eval_frontend_agent",
      eval_case_result_id: "case_frontend_agent",
      gold_set_case_id: "gold_frontend_agent",
      status: "passed",
      metric_keys: ["evidence_coverage", "trace_replayability"],
      evidence_metric_keys: ["citation_coverage"],
      trajectory_metric_keys: ["tool_order"],
    },
    improvement: {
      baseline_status: "missing",
      improvement_status: "no_baseline",
      release_blocked: false,
      improved_metric_keys: [],
      regressed_metric_keys: [],
      improvement_log: [],
    },
    replay_ready: true,
    missing_replay_requirements: [],
  };
}
